export const GAME_BALANCE = Object.freeze({
  PLAYER_SPEED: 3.9,
  PLAYER_RADIUS: 0.38,
  KNOCKBACK_DISTANCE: 0.82,
  BOT_SPEED: 2.05,
  DASH_DISTANCE: 1.68,
  DASH_COOLDOWN_MS: 2500,
  CORE_FUSE_SECONDS: 2.35,
  CORE_RANGE: 3,
  CORE_CAPACITY: 4,
  FLUX_SLOW_MS: 2200,
  FLUX_DOWNED_MS: 6000,
  THROW_RANGE: 3,
  THROW_DURATION_MS: 620,
  COUNTDOWN_SECONDS: 3,
  MATCH_SECONDS: 180,
})

export type GameBalance = typeof GAME_BALANCE
